name: Cleanup Public ARO Resources
on: [workflow_dispatch]

jobs: 
  cleanup_rg:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AAD_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION }}

    - name: hub cleanup
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.RESOURCEGROUP }}
        template: ./modules/resource_group_cleanup.bicep
        deploymentMode: Complete
        deploymentName: public-aro-resource-cleanup-github